name: ResistanceCalculator
options:
  deploymentTarget:
    iOS: 17.0

schemes:
  Local:
    build:
      targets:
        Local: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: ResistanceCalculatorTests
          parallelizable: true
          randomExecutionOrder: true
        - name: ResistanceCalculatorUITests
          parallelizable: false
          randomExecutionOrder: false
  Production:
    build:
      targets:
        Production: all
    run:
      config: Debug

targets:
  Local:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ResistanceCalculator
      # - path: Config/Local
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swiswiswift.ResistanceCalculator
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: ResistanceCalculator/Info.plist
        MARKETING_VERSION: 3.1.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Local
  Production:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ResistanceCalculator
      # - path: Config/Production
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: resistanceCalc.biz.sciencetools
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 5RH346BQ66
        INFOPLIST_FILE: ResistanceCalculator/Info.plist
        MARKETING_VERSION: 3.1.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Production
  ResistanceCalculatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ResistanceCalculatorTests
    settings:
      base:
        INFOPLIST_FILE: ResistanceCalculatorTests/Info.plist
    dependencies:
      - target: Local
  ResistanceCalculatorUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - ResistanceCalculatorUITests
    settings:
      base:
        INFOPLIST_FILE: ResistanceCalculatorUITests/Info.plist
    dependencies:
      - target: Local

