name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app

jobs:
  build:
    runs-on: macos-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version

    # Mintのインストール
    - name: Install Mint
      run: brew install mint

    - name: Mint Version
      run: mint --version

    # Mintで管理しているライブラリのインストール
    - name: Install Mint Library
      run: mint bootstrap

    # LS
    - name: ls
      run: ls

    # Mintでプロジェクトファイルを作成
    - name: Generate Project
      run: mint run xcodegen xcodegen generate

    # # テストを実行
    # - name: Run Tests
    #   run:  xcodebuild -project ResistanceCalculator.xcodeproj -scheme "Local" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test

